version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: worldgdp
      MYSQL_USER: ola
      MYSQL_PASSWORD: ola
    ports:
      - "3307:3306" # Change the host port to 3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
